spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/studentms?setUnicode=true&characterEncoding=utf8mb4&useAffectedRows=true
    url: jdbc:mysql://localhost:3306/studentms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: duan783809979


mybatis-plus:
  type-aliases-package: com.duan.server.entity
  mapper-locations: classpath:mapper/*.xml